### ISSUE TITLE
not working this modul

### ISSUE THREAD

**Issue by rab14191** [prince108/Magento2-Buynow#1]
this modul not working

**Comment by prince108** [comment]
@rab14191  Please provide your issue in details. This module working very fine in default magento 2 setup.

**Comment by rab14191** [comment]
When i click on  buy now then redirect to  http://127.0.0.1/checkout/  which not found
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

**Comment by prince108** [comment]
@rab14191 Please check now issue solve with localhost. You just need to update this file from latest reposition 
File:  Magento2-Buynow/app/code/Prince/Buynow/Controller/Cart/Add.php

**Comment by rab14191** [comment]
can you give me ur contact email id?
