### ISSUE TITLE
BuyNow button works but

### ISSUE THREAD

**Issue by gcampedelli** [prince108/Magento2-Buynow#2]
The button works, but there is a bug I identified. 
When there are products in the cart, it redirects to cart but eliminate all other products. 
Any possible fix?

**Comment by prince108** [comment]
Hi gcampedelli,
Thank you for posting issue. Your issue has been solved. Please check again with Buy Now.

**Comment by prince108** [comment]
@gcampedelli , if you want to keep only your added product in checkout you can uncomment line no 39 at

> app/code/Prince/Buynow/Controller/Cart/Add.php

```
// Uncomment this if you want only your added product in cart
//$this->cart->truncate();
```
