### ISSUE TITLE
Your Module is not working at Magento 2.1.7

### ISSUE THREAD

**Issue by kikinbenshakib** [prince108/Magento2-Buynow#3]
I have configured of your module in Magento 2.x but is not showing extra button.

**Comment by prince108** [comment]
Hi kikinbenshakib,

This module is tested and verified in Version Magento 2.1.3, 2.1.4, 2.1.5, 2.1.6 and 2.1.7.
Please make sure you follow the proper installation process. Also check if another module conflict.

**Here is latest screenshot with version Magento 2.1.7**

![magento 2 1 7](https://user-images.githubusercontent.com/24751863/27996700-937cdb66-6505-11e7-806b-2ed409aa9eff.png)
