### ISSUE TITLE
Module is not working to the third Party theme

### ISSUE THREAD

**Issue by kikinbenshakib** [prince108/magento2-buynow#4]
I installed this module to third party theme to check that, but the module is working on fresh luma theme. In the third party theme, it just working for Configurable products but not working for simple products.

Could you check it to third party theme ?

Thanks

**Comment by prince108** [comment]
Hi,

Change reference block name `<referenceBlock name="product.info.addtocart">` as per your custom theme at `app/code/Prince/Buynow/view/frontend/layout/catalog_product_view.xml`.

Also change form id `#product_addtocart_form` as per your theme at
`app/code/Prince/Buynow/view/frontend/templates/buynow.phtml`
